name = "cf-llm-shadoway"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "cf-llm-shadoway"

[vars]
AUTH_TOKEN = "your-secure-token-here"
DEBUG_MODE = "false"
DEFAULT_PROVIDER = "gemini"